<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>BoltSnap</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <!-- 常駐アプリのため、メモリとサイズを最優先で削る -->
    <UseSystemResourceKeys>true</UseSystemResourceKeys>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <TieredPGO>false</TieredPGO>
    <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
    <AutoreleasePoolSupport>false</AutoreleasePoolSupport>
    <EventSourceSupport>false</EventSourceSupport>
    <IlcOptimizationPreference>Size</IlcOptimizationPreference>
    <IlcGenerateStackTraceData>false</IlcGenerateStackTraceData>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BoltSnap.Core\BoltSnap.Core.csproj" />
  </ItemGroup>
</Project>
